--generated by chatgpt to insert some of our plot tags onto how to train your dragon

INSERT INTO movie_plot_tags (
    imdb_id,
    plot_tag_id,
    created_at,
    created_by_user_id
)
SELECT
    'tt26743210',
    pt.plot_tag_id,
    NOW(),
    1
FROM plot_tags pt
WHERE pt.tag_text_norm IN (
    'coming_of_age',
    'heros_journey',
    'underdog_story',
    'reluctant_hero',
    'self_discovery',
    'identity_and_belonging',
    'destiny_fulfilled',
    'broken_family',
    'parenting_challenges',
    'mentor_student',
    'found_family',
    'culture_clash',
    'good_vs_evil',
    'war_story',
    'resistance_movement',
    'survival',
    'survival_against_odds',
    'monster_hunt',
    'mythology_inspired',
    'epic_fantasy',
    'awakening_power',
    'moral_dilemma',
    'social_injustice',
    'identity_crisis',
    'bittersweet_ending',
    'full_circle_ending',
    'rivalry',
    'training_montage',
    'transformation'
);