using System;
using System.Linq;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using FindMyFlickWebsite.Server.DataModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;


//coppilot generated by asking it to create a controller to handle user profile management, including getting and updating profile
//information. the profile information is stored as claims on the user, which is a simple approach that avoids needing to change
//the Identity schema or create a separate profile entity. the controller has two endpoints:
//a GET endpoint to retrieve the current user's profile information, and a PUT endpoint to update the profile information.
//both endpoints require authentication and will return appropriate responses based on the success or failure of the operations.
namespace FindMyFlickWebsite.Server.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    [Authorize]
    public class ProfileController : ControllerBase
    {
        private readonly UserManager<IdentityUser> _userManager;

        public ProfileController(UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
        }

        // GET: api/profile
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Get()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null) return Unauthorized();

            var claims = await _userManager.GetClaimsAsync(user);

            var genresValue = claims.FirstOrDefault(c => c.Type == "favorite_genres")?.Value ?? string.Empty;
            var favoriteGenres = string.IsNullOrWhiteSpace(genresValue)
                ? new List<string>()
                : genresValue.Split(',', StringSplitOptions.RemoveEmptyEntries).Select(s => s.Trim()).ToList();

            var theme = claims.FirstOrDefault(c => c.Type == "theme")?.Value ?? string.Empty;
            var bio = claims.FirstOrDefault(c => c.Type == "bio")?.Value ?? string.Empty;

            var dto = new ProfileDto
            {
                Username = user.UserName ?? string.Empty,
                Email = user.Email ?? string.Empty,
                FavoriteGenres = favoriteGenres,
                Theme = theme,
                Bio = bio
            };

            return Ok(dto);
        }

        // PUT: api/profile
        [HttpPut]
        [Authorize]
        public async Task<IActionResult> Update([FromBody] ProfileUpdate model)
        {
            if (model == null) return BadRequest("Invalid payload.");

            var user = await _userManager.GetUserAsync(User);
            if (user == null) return Unauthorized();

            var existingClaims = await _userManager.GetClaimsAsync(user);
            var claimsToRemove = existingClaims
                .Where(c => c.Type == "favorite_genres" || c.Type == "theme" || c.Type == "bio")
                .ToList();

            if (claimsToRemove.Any())
            {
                var removeResult = await _userManager.RemoveClaimsAsync(user, claimsToRemove);
                if (!removeResult.Succeeded)
                    return StatusCode(500, removeResult.Errors);
            }

        var genresValue = (model.FavoriteGenres ?? Enumerable.Empty<string>()).Any()
    ? string.Join(",", model.FavoriteGenres ?? Enumerable.Empty<string>())
    : string.Empty;

            var newClaims = new List<Claim>
            {
                new Claim("favorite_genres", genresValue),
                new Claim("theme", model.Theme ?? string.Empty),
                new Claim("bio", model.Bio ?? string.Empty)
            };

            var addResult = await _userManager.AddClaimsAsync(user, newClaims);
            if (!addResult.Succeeded)
                return StatusCode(500, addResult.Errors);

            var response = new ProfileDto
            {
                Username = user.UserName ?? string.Empty,
                Email = user.Email ?? string.Empty,
                FavoriteGenres = model.FavoriteGenres ?? new List<string>(),
                Theme = model.Theme ?? string.Empty,
                Bio = model.Bio ?? string.Empty
            };

            return Ok(response);
        }
    }
}