// <auto-generated />
using System.Collections.Generic;
using FindMyFlickWebsite.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FindMyFlickWebsite.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260125220016_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FindMyFlickWebsite.Server.Models.Movies", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("AgeRating")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "age rating");

                    b.Property<List<string>>("Genre")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasAnnotation("Relational:JsonPropertyName", "genre");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Poster")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "poster");

                    b.Property<List<string>>("StreamingServices")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasAnnotation("Relational:JsonPropertyName", "streaming services");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "summary");

                    b.Property<double>("UserRatings")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "user ratings");

                    b.Property<bool>("UserWatchStatus")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "userWatchStatus");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "Year");

                    b.HasKey("ID");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.Models.Movies", b =>
                {
                    b.OwnsMany("FindMyFlickWebsite.Server.Models.Movies+TagVote", "TagVotes", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Downvotes")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "downvotes");

                            b1.Property<int>("MovieId")
                                .HasColumnType("integer");

                            b1.Property<int>("TagID")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "tagID");

                            b1.Property<int>("Upvotes")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "upvotes");

                            b1.HasKey("Id");

                            b1.HasIndex("MovieId");

                            b1.ToTable("TagVotes", (string)null);

                            b1.HasAnnotation("Relational:JsonPropertyName", "tagVotes");

                            b1.WithOwner()
                                .HasForeignKey("MovieId");
                        });

                    b.OwnsOne("FindMyFlickWebsite.Server.Models.Tags", "Tags", b1 =>
                        {
                            b1.Property<int>("MoviesID")
                                .HasColumnType("integer");

                            b1.HasKey("MoviesID");

                            b1.ToTable("Tags", (string)null);

                            b1.HasAnnotation("Relational:JsonPropertyName", "Tags");

                            b1.WithOwner()
                                .HasForeignKey("MoviesID");

                            b1.OwnsMany("FindMyFlickWebsite.Server.Models.Tags+PersonTag", "PersonTags", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("TagID")
                                        .HasColumnType("integer")
                                        .HasAnnotation("Relational:JsonPropertyName", "tagID");

                                    b2.Property<string>("TagName")
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "tagName");

                                    b2.Property<string>("TagType")
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "tagType");

                                    b2.Property<int>("TagsId")
                                        .HasColumnType("integer");

                                    b2.HasKey("Id");

                                    b2.HasIndex("TagsId");

                                    b2.ToTable("PersonTags", (string)null);

                                    b2.HasAnnotation("Relational:JsonPropertyName", "Person tags");

                                    b2.WithOwner()
                                        .HasForeignKey("TagsId");
                                });

                            b1.OwnsMany("FindMyFlickWebsite.Server.Models.Tags+PlotTag", "PlotTags", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("TagID")
                                        .HasColumnType("integer")
                                        .HasAnnotation("Relational:JsonPropertyName", "tagID");

                                    b2.Property<string>("TagName")
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "tagName");

                                    b2.Property<string>("TagType")
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "tagType");

                                    b2.Property<int>("TagsId")
                                        .HasColumnType("integer");

                                    b2.HasKey("Id");

                                    b2.HasIndex("TagsId");

                                    b2.ToTable("PlotTags", (string)null);

                                    b2.HasAnnotation("Relational:JsonPropertyName", "Plot tags");

                                    b2.WithOwner()
                                        .HasForeignKey("TagsId");
                                });

                            b1.OwnsMany("FindMyFlickWebsite.Server.Models.Tags+TriggerTag", "TriggerTags", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("TagID")
                                        .HasColumnType("integer")
                                        .HasAnnotation("Relational:JsonPropertyName", "tagID");

                                    b2.Property<string>("TagName")
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "tagName");

                                    b2.Property<string>("TagType")
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "tagType");

                                    b2.Property<int>("TagsId")
                                        .HasColumnType("integer");

                                    b2.HasKey("Id");

                                    b2.HasIndex("TagsId");

                                    b2.ToTable("TriggerTags", (string)null);

                                    b2.HasAnnotation("Relational:JsonPropertyName", "Trigger tags");

                                    b2.WithOwner()
                                        .HasForeignKey("TagsId");
                                });

                            b1.Navigation("PersonTags");

                            b1.Navigation("PlotTags");

                            b1.Navigation("TriggerTags");
                        });

                    b.Navigation("TagVotes");

                    b.Navigation("Tags")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
