// <auto-generated />
using System;
using FindMyFlickWebsite.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FindMyFlickWebsite.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260307013655_AddIdentity")]
    partial class AddIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.Collection", b =>
                {
                    b.Property<int>("TmdbCollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_collection_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TmdbCollectionId"));

                    b.Property<string>("BackdropUrl")
                        .HasColumnType("text")
                        .HasColumnName("backdrop_url");

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("collection_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("text")
                        .HasColumnName("poster_url");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TmdbCollectionId")
                        .HasName("pk_collections");

                    b.ToTable("collections", (string)null);
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.DtddOverride", b =>
                {
                    b.Property<string>("ImdbId")
                        .HasColumnType("text")
                        .HasColumnName("imdb_id");

                    b.Property<int>("DtddMediaId")
                        .HasColumnType("integer")
                        .HasColumnName("dtdd_media_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ImdbId", "DtddMediaId")
                        .HasName("pk_dtdd_overrides");

                    b.HasIndex("ImdbId")
                        .IsUnique();

                    b.ToTable("dtdd_overrides", (string)null);
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.Genre", b =>
                {
                    b.Property<int>("TmdbGenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_genre_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TmdbGenreId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("genre_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TmdbGenreId")
                        .HasName("pk_genres");

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.Keyword", b =>
                {
                    b.Property<int>("TmdbKeywordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_keyword_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TmdbKeywordId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("KeywordName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("keyword_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TmdbKeywordId")
                        .HasName("pk_keywords");

                    b.ToTable("keywords", (string)null);
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.Movie", b =>
                {
                    b.Property<string>("ImdbId")
                        .HasColumnType("text")
                        .HasColumnName("imdb_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("media_type");

                    b.Property<string>("MpaaRating")
                        .HasColumnType("text")
                        .HasColumnName("mpaa_rating");

                    b.Property<string>("OriginalLanguage")
                        .HasColumnType("text")
                        .HasColumnName("original_language");

                    b.Property<string>("PlotSummary")
                        .HasColumnType("text")
                        .HasColumnName("plot_summary");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("text")
                        .HasColumnName("poster_url");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer")
                        .HasColumnName("release_year");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("runtime_minutes");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Tagline")
                        .HasColumnType("text")
                        .HasColumnName("tagline");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ImdbId")
                        .HasName("pk_movies_imdb_id");

                    b.ToTable("movies", (string)null);
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.MovieCast", b =>
                {
                    b.Property<string>("TmdbCreditId")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_credit_id");

                    b.Property<int?>("CastOrder")
                        .HasColumnType("integer")
                        .HasColumnName("cast_order");

                    b.Property<string>("CharacterName")
                        .HasColumnType("text")
                        .HasColumnName("character_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImdbId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("imdb_id");

                    b.Property<int>("TmdbPersonId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_person_id");

                    b.HasKey("TmdbCreditId")
                        .HasName("pk_movie_cast");

                    b.HasIndex("ImdbId");

                    b.HasIndex("TmdbPersonId");

                    b.ToTable("movie_cast", (string)null);
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.MovieCollection", b =>
                {
                    b.Property<string>("ImdbId")
                        .HasColumnType("text")
                        .HasColumnName("imdb_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("TmdbCollectionId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_collection_id");

                    b.HasKey("ImdbId")
                        .HasName("pk_movie_collections");

                    b.HasIndex("TmdbCollectionId");

                    b.ToTable("movie_collections", (string)null);
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.MovieCrew", b =>
                {
                    b.Property<string>("TmdbCreditId")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_credit_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("ImdbId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("imdb_id");

                    b.Property<string>("Job")
                        .HasColumnType("text")
                        .HasColumnName("job");

                    b.Property<int>("TmdbPersonId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_person_id");

                    b.HasKey("TmdbCreditId")
                        .HasName("pk_movie_crew");

                    b.HasIndex("ImdbId");

                    b.HasIndex("TmdbPersonId");

                    b.ToTable("movie_crew", (string)null);
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.MovieDtddTitle", b =>
                {
                    b.Property<string>("ImdbId")
                        .HasColumnType("text")
                        .HasColumnName("imdb_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DtddImdbId")
                        .HasColumnType("text")
                        .HasColumnName("dtdd_imdb_id");

                    b.Property<int?>("DtddMediaId")
                        .HasColumnType("integer")
                        .HasColumnName("dtdd_media_id");

                    b.Property<int?>("DtddReleaseYear")
                        .HasColumnType("integer")
                        .HasColumnName("dtdd_release_year");

                    b.Property<string>("DtddTitle")
                        .HasColumnType("text")
                        .HasColumnName("dtdd_title");

                    b.Property<int?>("DtddTitleId")
                        .HasColumnType("integer")
                        .HasColumnName("dtdd_title_id");

                    b.Property<int?>("DtddTmdbId")
                        .HasColumnType("integer")
                        .HasColumnName("dtdd_tmdb_id");

                    b.Property<string>("MatchMethod")
                        .HasColumnType("text")
                        .HasColumnName("match_method");

                    b.Property<decimal?>("MatchScore")
                        .HasColumnType("numeric")
                        .HasColumnName("match_score");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ImdbId")
                        .HasName("pk_movie_dtdd_titles");

                    b.ToTable("movie_dtdd_titles", (string)null);
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.MovieGenre", b =>
                {
                    b.Property<string>("ImdbId")
                        .HasColumnType("text")
                        .HasColumnName("imdb_id");

                    b.Property<int>("TmdbGenreId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_genre_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("ImdbId", "TmdbGenreId")
                        .HasName("pk_movie_genres");

                    b.HasIndex("TmdbGenreId");

                    b.ToTable("movie_genres", (string)null);
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.MovieKeyword", b =>
                {
                    b.Property<string>("ImdbId")
                        .HasColumnType("text")
                        .HasColumnName("imdb_id");

                    b.Property<int>("TmdbKeywordId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_keyword_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("ImdbId", "TmdbKeywordId")
                        .HasName("pk_movie_keywords");

                    b.HasIndex("TmdbKeywordId");

                    b.ToTable("movie_keywords", (string)null);
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.MovieStreaming", b =>
                {
                    b.Property<string>("ImdbId")
                        .HasColumnType("text")
                        .HasColumnName("imdb_id");

                    b.Property<int>("TmdbProviderId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_provider_id");

                    b.Property<string>("OfferType")
                        .HasColumnType("text")
                        .HasColumnName("offer_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("ImdbId", "TmdbProviderId", "OfferType")
                        .HasName("pk_movie_streaming");

                    b.HasIndex("TmdbProviderId");

                    b.ToTable("movie_streaming", (string)null);
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.MovieWarning", b =>
                {
                    b.Property<string>("ImdbId")
                        .HasColumnType("text")
                        .HasColumnName("imdb_id");

                    b.Property<int>("DtddTopicId")
                        .HasColumnType("integer")
                        .HasColumnName("dtdd_topic_id");

                    b.Property<string>("Answer")
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool?>("IsSpoiler")
                        .HasColumnType("boolean")
                        .HasColumnName("is_spoiler");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WarningComment")
                        .HasColumnType("text")
                        .HasColumnName("warning_comment");

                    b.HasKey("ImdbId", "DtddTopicId")
                        .HasName("pk_movie_warnings");

                    b.HasIndex("DtddTopicId");

                    b.ToTable("movie_warnings", (string)null);
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.Person", b =>
                {
                    b.Property<int>("TmdbPersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_person_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TmdbPersonId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("KnownForDepartment")
                        .HasColumnType("text")
                        .HasColumnName("known_for_department");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("person_name");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_url");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TmdbPersonId")
                        .HasName("pk_people");

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.StreamingProvider", b =>
                {
                    b.Property<int>("TmdbProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_provider_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TmdbProviderId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DisplayPriority")
                        .HasColumnType("integer")
                        .HasColumnName("display_priority");

                    b.Property<string>("LogoPath")
                        .HasColumnType("text")
                        .HasColumnName("logo_path");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TmdbProviderId")
                        .HasName("pk_streaming_providers");

                    b.ToTable("streaming_providers", (string)null);
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.Warning", b =>
                {
                    b.Property<int>("DtddTopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("dtdd_topic_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DtddTopicId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("ParentDtddTopicId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_dtdd_topic_id");

                    b.Property<short?>("Tier")
                        .HasColumnType("smallint")
                        .HasColumnName("tier");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic_name");

                    b.Property<string>("TopicType")
                        .HasColumnType("text")
                        .HasColumnName("topic_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("DtddTopicId")
                        .HasName("pk_warnings");

                    b.HasIndex("ParentDtddTopicId");

                    b.ToTable("warnings", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.DtddOverride", b =>
                {
                    b.HasOne("FindMyFlickWebsite.Server.DataModels.Movie", "Imdb")
                        .WithOne("DtddOverride")
                        .HasForeignKey("FindMyFlickWebsite.Server.DataModels.DtddOverride", "ImdbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dtdd_overrides_movies_imdb");

                    b.Navigation("Imdb");
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.MovieCast", b =>
                {
                    b.HasOne("FindMyFlickWebsite.Server.DataModels.Movie", "Imdb")
                        .WithMany("MovieCasts")
                        .HasForeignKey("ImdbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_cast_movies_imdb");

                    b.HasOne("FindMyFlickWebsite.Server.DataModels.Person", "TmdbPerson")
                        .WithMany("MovieCasts")
                        .HasForeignKey("TmdbPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_cast_people_tmdb_person_id");

                    b.Navigation("Imdb");

                    b.Navigation("TmdbPerson");
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.MovieCollection", b =>
                {
                    b.HasOne("FindMyFlickWebsite.Server.DataModels.Movie", "Imdb")
                        .WithOne("MovieCollection")
                        .HasForeignKey("FindMyFlickWebsite.Server.DataModels.MovieCollection", "ImdbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_collections_movies_imdb");

                    b.HasOne("FindMyFlickWebsite.Server.DataModels.Collection", "TmdbCollection")
                        .WithMany("MovieCollections")
                        .HasForeignKey("TmdbCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_collections_collections_tmdb_collection_id");

                    b.Navigation("Imdb");

                    b.Navigation("TmdbCollection");
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.MovieCrew", b =>
                {
                    b.HasOne("FindMyFlickWebsite.Server.DataModels.Movie", "Imdb")
                        .WithMany("MovieCrews")
                        .HasForeignKey("ImdbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_crew_movies_imdb");

                    b.HasOne("FindMyFlickWebsite.Server.DataModels.Person", "TmdbPerson")
                        .WithMany("MovieCrews")
                        .HasForeignKey("TmdbPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_crew_people_tmdb_person_id");

                    b.Navigation("Imdb");

                    b.Navigation("TmdbPerson");
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.MovieDtddTitle", b =>
                {
                    b.HasOne("FindMyFlickWebsite.Server.DataModels.Movie", "Imdb")
                        .WithOne("MovieDtddTitle")
                        .HasForeignKey("FindMyFlickWebsite.Server.DataModels.MovieDtddTitle", "ImdbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_dtdd_titles_movies_imdb");

                    b.Navigation("Imdb");
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.MovieGenre", b =>
                {
                    b.HasOne("FindMyFlickWebsite.Server.DataModels.Movie", "Imdb")
                        .WithMany("MovieGenres")
                        .HasForeignKey("ImdbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_genres_movies_imdb");

                    b.HasOne("FindMyFlickWebsite.Server.DataModels.Genre", "TmdbGenre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("TmdbGenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_genres_genres_tmdb_genre_id");

                    b.Navigation("Imdb");

                    b.Navigation("TmdbGenre");
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.MovieKeyword", b =>
                {
                    b.HasOne("FindMyFlickWebsite.Server.DataModels.Movie", "Imdb")
                        .WithMany("MovieKeywords")
                        .HasForeignKey("ImdbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_keywords_movies_imdb");

                    b.HasOne("FindMyFlickWebsite.Server.DataModels.Keyword", "TmdbKeyword")
                        .WithMany("MovieKeywords")
                        .HasForeignKey("TmdbKeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_keywords_keywords_tmdb_keyword_id");

                    b.Navigation("Imdb");

                    b.Navigation("TmdbKeyword");
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.MovieStreaming", b =>
                {
                    b.HasOne("FindMyFlickWebsite.Server.DataModels.Movie", "Imdb")
                        .WithMany("MovieStreamings")
                        .HasForeignKey("ImdbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_streaming_movies_imdb");

                    b.HasOne("FindMyFlickWebsite.Server.DataModels.StreamingProvider", "TmdbProvider")
                        .WithMany("MovieStreamings")
                        .HasForeignKey("TmdbProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_streaming_providers_tmdb_provider_id");

                    b.Navigation("Imdb");

                    b.Navigation("TmdbProvider");
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.MovieWarning", b =>
                {
                    b.HasOne("FindMyFlickWebsite.Server.DataModels.Warning", "DtddTopic")
                        .WithMany("MovieWarnings")
                        .HasForeignKey("DtddTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_warnings_warnings_dtdd_topic_id");

                    b.HasOne("FindMyFlickWebsite.Server.DataModels.Movie", "Imdb")
                        .WithMany("MovieWarnings")
                        .HasForeignKey("ImdbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_warnings_movies_imdb");

                    b.Navigation("DtddTopic");

                    b.Navigation("Imdb");
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.Warning", b =>
                {
                    b.HasOne("FindMyFlickWebsite.Server.DataModels.Warning", "ParentDtddTopic")
                        .WithMany("InverseParentDtddTopic")
                        .HasForeignKey("ParentDtddTopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_warnings_parent_dtdd_topic");

                    b.Navigation("ParentDtddTopic");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.Collection", b =>
                {
                    b.Navigation("MovieCollections");
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.Keyword", b =>
                {
                    b.Navigation("MovieKeywords");
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.Movie", b =>
                {
                    b.Navigation("DtddOverride");

                    b.Navigation("MovieCasts");

                    b.Navigation("MovieCollection");

                    b.Navigation("MovieCrews");

                    b.Navigation("MovieDtddTitle");

                    b.Navigation("MovieGenres");

                    b.Navigation("MovieKeywords");

                    b.Navigation("MovieStreamings");

                    b.Navigation("MovieWarnings");
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.Person", b =>
                {
                    b.Navigation("MovieCasts");

                    b.Navigation("MovieCrews");
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.StreamingProvider", b =>
                {
                    b.Navigation("MovieStreamings");
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.DataModels.Warning", b =>
                {
                    b.Navigation("InverseParentDtddTopic");

                    b.Navigation("MovieWarnings");
                });
#pragma warning restore 612, 618
        }
    }
}
