// <auto-generated />
using System;
using FindMyFlickWebsite.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FindMyFlickWebsite.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260126010621_MapMovieColumns")]
    partial class MapMovieColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FindMyFlickWebsite.Server.Models.Movies", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("imdb_id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("AgeRating")
                        .HasColumnType("text")
                        .HasColumnName("mpaa_rating")
                        .HasAnnotation("Relational:JsonPropertyName", "mpaa_rating");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("MediaType")
                        .HasColumnType("text")
                        .HasColumnName("media_type")
                        .HasAnnotation("Relational:JsonPropertyName", "media_type");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("title")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.Property<string>("OriginalLanguage")
                        .HasColumnType("text")
                        .HasColumnName("original_language")
                        .HasAnnotation("Relational:JsonPropertyName", "original_language");

                    b.Property<string>("Poster")
                        .HasColumnType("text")
                        .HasColumnName("poster_url")
                        .HasAnnotation("Relational:JsonPropertyName", "poster_url");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("runtime_minutes")
                        .HasAnnotation("Relational:JsonPropertyName", "runtime_minutes");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("plot_summary")
                        .HasAnnotation("Relational:JsonPropertyName", "plot_summary");

                    b.Property<string>("Tagline")
                        .HasColumnType("text")
                        .HasColumnName("tagline")
                        .HasAnnotation("Relational:JsonPropertyName", "tagline");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_id")
                        .HasAnnotation("Relational:JsonPropertyName", "tmdb_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasAnnotation("Relational:JsonPropertyName", "updated_at");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("release_year")
                        .HasAnnotation("Relational:JsonPropertyName", "release_year");

                    b.HasKey("ID");

                    b.ToTable("movies", (string)null);
                });

            modelBuilder.Entity("FindMyFlickWebsite.Server.Models.Movies", b =>
                {
                    b.OwnsOne("FindMyFlickWebsite.Server.Models.Tags", "Tags", b1 =>
                        {
                            b1.Property<int>("MoviesID")
                                .HasColumnType("integer");

                            b1.HasKey("MoviesID");

                            b1.ToTable("tags", (string)null);

                            b1.HasAnnotation("Relational:JsonPropertyName", "Tags");

                            b1.WithOwner()
                                .HasForeignKey("MoviesID");

                            b1.OwnsMany("FindMyFlickWebsite.Server.Models.Tags+PersonTag", "PersonTags", b2 =>
                                {
                                    b2.Property<int>("id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("id"));

                                    b2.Property<int>("TagID")
                                        .HasColumnType("integer")
                                        .HasColumnName("tag_id")
                                        .HasAnnotation("Relational:JsonPropertyName", "tagID");

                                    b2.Property<string>("TagName")
                                        .HasColumnType("text")
                                        .HasColumnName("tag_name")
                                        .HasAnnotation("Relational:JsonPropertyName", "tagName");

                                    b2.Property<string>("TagType")
                                        .HasColumnType("text")
                                        .HasColumnName("tag_type")
                                        .HasAnnotation("Relational:JsonPropertyName", "tagType");

                                    b2.Property<int>("tags_id")
                                        .HasColumnType("integer");

                                    b2.HasKey("id");

                                    b2.HasIndex("tags_id");

                                    b2.ToTable("person_tags", (string)null);

                                    b2.HasAnnotation("Relational:JsonPropertyName", "Person tags");

                                    b2.WithOwner()
                                        .HasForeignKey("tags_id");
                                });

                            b1.OwnsMany("FindMyFlickWebsite.Server.Models.Tags+PlotTag", "PlotTags", b2 =>
                                {
                                    b2.Property<int>("id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("id"));

                                    b2.Property<int>("TagID")
                                        .HasColumnType("integer")
                                        .HasColumnName("tag_id")
                                        .HasAnnotation("Relational:JsonPropertyName", "tagID");

                                    b2.Property<string>("TagName")
                                        .HasColumnType("text")
                                        .HasColumnName("tag_name")
                                        .HasAnnotation("Relational:JsonPropertyName", "tagName");

                                    b2.Property<string>("TagType")
                                        .HasColumnType("text")
                                        .HasColumnName("tag_type")
                                        .HasAnnotation("Relational:JsonPropertyName", "tagType");

                                    b2.Property<int>("tags_id")
                                        .HasColumnType("integer");

                                    b2.HasKey("id");

                                    b2.HasIndex("tags_id");

                                    b2.ToTable("plot_tags", (string)null);

                                    b2.HasAnnotation("Relational:JsonPropertyName", "Plot tags");

                                    b2.WithOwner()
                                        .HasForeignKey("tags_id");
                                });

                            b1.OwnsMany("FindMyFlickWebsite.Server.Models.Tags+TriggerTag", "TriggerTags", b2 =>
                                {
                                    b2.Property<int>("id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("id"));

                                    b2.Property<int>("TagID")
                                        .HasColumnType("integer")
                                        .HasColumnName("tag_id")
                                        .HasAnnotation("Relational:JsonPropertyName", "tagID");

                                    b2.Property<string>("TagName")
                                        .HasColumnType("text")
                                        .HasColumnName("tag_name")
                                        .HasAnnotation("Relational:JsonPropertyName", "tagName");

                                    b2.Property<string>("TagType")
                                        .HasColumnType("text")
                                        .HasColumnName("tag_type")
                                        .HasAnnotation("Relational:JsonPropertyName", "tagType");

                                    b2.Property<int>("tags_id")
                                        .HasColumnType("integer");

                                    b2.HasKey("id");

                                    b2.HasIndex("tags_id");

                                    b2.ToTable("trigger_tags", (string)null);

                                    b2.HasAnnotation("Relational:JsonPropertyName", "Trigger tags");

                                    b2.WithOwner()
                                        .HasForeignKey("tags_id");
                                });

                            b1.Navigation("PersonTags");

                            b1.Navigation("PlotTags");

                            b1.Navigation("TriggerTags");
                        });

                    b.OwnsMany("FindMyFlickWebsite.Server.Models.Movies+GenreEntry", "GenreEntries", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<int>("TmdbGenreId")
                                .HasColumnType("integer")
                                .HasColumnName("tmdb_genre_id")
                                .HasAnnotation("Relational:JsonPropertyName", "tmdb_genre_id");

                            b1.Property<int>("imdb_id")
                                .HasColumnType("integer");

                            b1.HasKey("id");

                            b1.HasIndex("imdb_id");

                            b1.ToTable("movie_genres", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("imdb_id");
                        });

                    b.OwnsMany("FindMyFlickWebsite.Server.Models.Movies+StreamingProvider", "StreamingProviders", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<string>("ProviderName")
                                .HasColumnType("text")
                                .HasColumnName("provider_name")
                                .HasAnnotation("Relational:JsonPropertyName", "provider_name");

                            b1.Property<int>("imdb_id")
                                .HasColumnType("integer");

                            b1.HasKey("id");

                            b1.HasIndex("imdb_id");

                            b1.ToTable("streaming_providers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("imdb_id");
                        });

                    b.OwnsMany("FindMyFlickWebsite.Server.Models.Movies+TagVote", "TagVotes", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<int>("Downvotes")
                                .HasColumnType("integer")
                                .HasColumnName("downvotes")
                                .HasAnnotation("Relational:JsonPropertyName", "downvotes");

                            b1.Property<int>("TagID")
                                .HasColumnType("integer")
                                .HasColumnName("tag_id")
                                .HasAnnotation("Relational:JsonPropertyName", "tagID");

                            b1.Property<int>("Upvotes")
                                .HasColumnType("integer")
                                .HasColumnName("upvotes")
                                .HasAnnotation("Relational:JsonPropertyName", "upvotes");

                            b1.Property<int>("movie_id")
                                .HasColumnType("integer");

                            b1.HasKey("id");

                            b1.HasIndex("movie_id");

                            b1.ToTable("tag_votes", (string)null);

                            b1.HasAnnotation("Relational:JsonPropertyName", "tagVotes");

                            b1.WithOwner()
                                .HasForeignKey("movie_id");
                        });

                    b.Navigation("GenreEntries");

                    b.Navigation("StreamingProviders");

                    b.Navigation("TagVotes");

                    b.Navigation("Tags")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
