--generated via inputting the code for these tables from my auto generated migration from VS into chatgpt
--and telling it to convert the code into sql queries

--commented out is ran first then rest was run
CREATE TABLE "AspNetUsers" (
    "Id" TEXT PRIMARY KEY,
    "UserName" VARCHAR(256),
    "NormalizedUserName" VARCHAR(256),
    "Email" VARCHAR(256),
    "NormalizedEmail" VARCHAR(256),
    "EmailConfirmed" BOOLEAN NOT NULL,
    "PasswordHash" TEXT,
    "SecurityStamp" TEXT,
    "ConcurrencyStamp" TEXT,
    "PhoneNumber" TEXT,
    "PhoneNumberConfirmed" BOOLEAN NOT NULL,
    "TwoFactorEnabled" BOOLEAN NOT NULL,
    "LockoutEnd" TIMESTAMPTZ,
    "LockoutEnabled" BOOLEAN NOT NULL,
    "AccessFailedCount" INTEGER NOT NULL
);
--
--CREATE TABLE "AspNetRoles" (
--    "Id" TEXT PRIMARY KEY,
--    "Name" VARCHAR(256),
--    "NormalizedName" VARCHAR(256),
--    "ConcurrencyStamp" TEXT
--);

--CREATE TABLE "AspNetRoleClaims" (
--    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    "RoleId" TEXT NOT NULL,
--    "ClaimType" TEXT,
--    "ClaimValue" TEXT,
--    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId"
--        FOREIGN KEY ("RoleId")
--        REFERENCES "AspNetRoles"("Id")
--        ON DELETE CASCADE
--);
--
--CREATE TABLE "AspNetUserClaims" (
--    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    "UserId" TEXT NOT NULL,
--    "ClaimType" TEXT,
--    "ClaimValue" TEXT,
--    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId"
--        FOREIGN KEY ("UserId")
--        REFERENCES "AspNetUsers"("Id")
--        ON DELETE CASCADE
--);
--
--CREATE TABLE "AspNetUserLogins" (
--    "LoginProvider" TEXT NOT NULL,
--    "ProviderKey" TEXT NOT NULL,
--    "ProviderDisplayName" TEXT,
--    "UserId" TEXT NOT NULL,
--    PRIMARY KEY ("LoginProvider", "ProviderKey"),
--    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId"
--        FOREIGN KEY ("UserId")
--        REFERENCES "AspNetUsers"("Id")
--        ON DELETE CASCADE
--);
--
--CREATE TABLE "AspNetUserRoles" (
--    "UserId" TEXT NOT NULL,
--    "RoleId" TEXT NOT NULL,
--    PRIMARY KEY ("UserId", "RoleId"),
--    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId"
--        FOREIGN KEY ("RoleId")
--        REFERENCES "AspNetRoles"("Id")
--        ON DELETE CASCADE,
--    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId"
--        FOREIGN KEY ("UserId")
--        REFERENCES "AspNetUsers"("Id")
--        ON DELETE CASCADE
--);
--
--CREATE TABLE "AspNetUserTokens" (
--    "UserId" TEXT NOT NULL,
--    "LoginProvider" TEXT NOT NULL,
--    "Name" TEXT NOT NULL,
--    "Value" TEXT,
--    PRIMARY KEY ("UserId", "LoginProvider", "Name"),
--    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId"
--        FOREIGN KEY ("UserId")
--        REFERENCES "AspNetUsers"("Id")
--        ON DELETE CASCADE
--);
--
--CREATE INDEX "IX_AspNetRoleClaims_RoleId"
--ON "AspNetRoleClaims" ("RoleId");
--
--CREATE UNIQUE INDEX "RoleNameIndex"
--ON "AspNetRoles" ("NormalizedName");
--
--CREATE INDEX "IX_AspNetUserClaims_UserId"
--ON "AspNetUserClaims" ("UserId");
--
--CREATE INDEX "IX_AspNetUserLogins_UserId"
--ON "AspNetUserLogins" ("UserId");
--
--CREATE INDEX "IX_AspNetUserRoles_RoleId"
--ON "AspNetUserRoles" ("RoleId");
--
--CREATE INDEX "EmailIndex"
--ON "AspNetUsers" ("NormalizedEmail");
--
--CREATE UNIQUE INDEX "UserNameIndex"
--ON "AspNetUsers" ("NormalizedUserName");